name: Bunnimage Frontend
on:
  push:
    branches:
      - bunnimage-frontend

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Setup Node Environment
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install Dependencies
        run: |
          npm install minimist
          npm install node-fetch
          
      - name: Get Count
        id: vars
        run: echo ::set-output name=count::$(node ./.bit/scripts/getProgress.js --repo=${{github.event.repository.name}} --owner=${{github.repository_owner}} )
      
      - name: Install Cypress
        run: npm install cypress
        
      - name: Step 51
        if: ${{steps.vars.outputs.count == 51 && github.event.head_commit.message != 'Update progress'}}
        run: node .bit/tests/spec.js --repo=${{github.event.repository.name}} --user=${{github.repository_owner}} --spec=cypress/integration/4.1.spec.js

      - name: Step 53
        if: ${{steps.vars.outputs.count == 53 && github.event.head_commit.message != 'Update progress'}}
        run: node .bit/tests/spec.js --repo=${{github.event.repository.name}} --user=${{github.repository_owner}} --spec=cypress/integration/4.2.spec.js

      - name: Step 55
        if: ${{steps.vars.outputs.count == 55 && github.event.head_commit.message != 'Update progress'}}
        run: node .bit/tests/spec.js --repo=${{github.event.repository.name}} --user=${{github.repository_owner}} --spec=cypress/integration/4.3.spec.js

      - name: Step 57
        if: ${{steps.vars.outputs.count == 57 && github.event.head_commit.message != 'Update progress'}}
        run: node .bit/tests/spec.js --repo=${{github.event.repository.name}} --user=${{github.repository_owner}} --spec=cypress/integration/4.4.spec.js

      - name: Check for branch
        if: ${{steps.vars.outputs.count > 57 && github.event.head_commit.message != 'Update progress'}}
        run: |
          node .bit/tests/wrongbranch.js
