name: Deep Secrets
on:
  push:
    branches:
      - deepsecrets

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Setup Node Environment
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Get Count
        id: vars
        run: echo ::set-output name=count::$(cat ./.bit/.progress)

      - name: Step 6
        if: ${{steps.vars.outputs.count == 32 && github.event.head_commit.message != 'Update progress'}}
        env:
          DEEPSECRETS_ENDPOINT: ${{ secrets.DEEPSECRETS_ENDPOINT }}
        run: |
          npm install node-fetch
          node .bit/tests/test.3.6.js
      - name: Step 7
        if: ${{steps.vars.outputs.count == 33 && github.event.head_commit.message != 'Update progress'}}
        env:
          DEEPSECRETS_ENDPOINT: ${{ secrets.DEEPSECRETS_ENDPOINT }}
        run: |
          npm install node-fetch
          node .bit/tests/test.3.7.js
      - name: Step 8
        if: ${{steps.vars.outputs.count == 34 && github.event.head_commit.message != 'Update progress'}}
        env:
          DEEPSECRETS_ENDPOINT: ${{ secrets.DEEPSECRETS_ENDPOINT }}
        run: |
          npm install node-fetch
          node .bit/tests/test.3.8.js
      - name: Check for branch
        if: ${{steps.vars.outputs.count > 34 && github.event.head_commit.message != 'Update progress'}}
        run: |
          node .bit/tests/wrongbranch.js