name: Deep Secrets
on:
  push:
    branches:
      - deepsecrets

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Setup Node Environment
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install Dependencies
        run: |
          npm install minimist
          npm install node-fetch
          
      - name: Get Count
        id: vars
        run: echo ::set-output name=count::$(node ./.bit/scripts/getProgress.js --repo=${{github.event.repository.name}} --owner=${{github.repository_owner}} )

      - name: Step 43
        if: ${{steps.vars.outputs.count == 43 && github.event.head_commit.message != 'Update progress'}}
        env:
          DEEPSECRETS_ENDPOINT: ${{ secrets.DEEPSECRETS_ENDPOINT }}
        run: |
          npm install node-fetch
          node .bit/tests/test.3.6.js --repo=${{github.event.repository.name}} --user=${{github.repository_owner}}
      - name: Step 45
        if: ${{steps.vars.outputs.count == 45 && github.event.head_commit.message != 'Update progress'}}
        env:
          DEEPSECRETS_ENDPOINT: ${{ secrets.DEEPSECRETS_ENDPOINT }}
        run: |
          npm install node-fetch
          node .bit/tests/test.3.7.js --repo=${{github.event.repository.name}} --user=${{github.repository_owner}}
      - name: Step 47
        if: ${{steps.vars.outputs.count == 47 && github.event.head_commit.message != 'Update progress'}}
        env:
          DEEPSECRETS_ENDPOINT: ${{ secrets.DEEPSECRETS_ENDPOINT }}
        run: |
          npm install node-fetch
          node .bit/tests/test.3.8.js --repo=${{github.event.repository.name}} --user=${{github.repository_owner}}
      - name: Check for branch
        if: ${{steps.vars.outputs.count > 47 && github.event.head_commit.message != 'Update progress'}}
        run: |
          node .bit/tests/wrongbranch.js
