name: Emotional Gifs
on:
  push:
    branches:
      - emotionalgifs

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Setup Node Environment
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install Dependencies
        run: |
          npm install minimist
          npm install node-fetch
             
      - name: Get Count
        id: vars
        run: echo ::set-output name=count::$(node ./.bit/scripts/getProgress.js --repo=${{github.event.repository.name}} --owner=${{github.repository_owner}} )

      - name: Step 17
        if: ${{steps.vars.outputs.count == 17 && github.event.head_commit.message != 'Update progress'}}
        env:
          EMOTIONAL_ENDPOINT: ${{ secrets.EMOTIONAL_ENDPOINT }}
        run: |
          npm install node-fetch
          npm install form-data
          node .bit/tests/test.2.2.js --repo=${{github.event.repository.name}} --user=${{github.repository_owner}}

      - name: Step 19
        if: ${{steps.vars.outputs.count == 19 && github.event.head_commit.message != 'Update progress'}}
        env:
          EMOTIONAL_ENDPOINT: ${{ secrets.EMOTIONAL_ENDPOINT }}
        run: |
          npm install node-fetch
          npm install form-data
          node .bit/tests/test.2.3.js --repo=${{github.event.repository.name}} --user=${{github.repository_owner}}

      - name: Step 21
        if: ${{steps.vars.outputs.count == 21 && github.event.head_commit.message != 'Update progress'}}
        env:
          EMOTIONAL_ENDPOINT: ${{ secrets.EMOTIONAL_ENDPOINT }}
        run: |
          npm install node-fetch
          npm install form-data
          node .bit/tests/test.2.4.js --repo=${{github.event.repository.name}} --user=${{github.repository_owner}}

      - name: Step 23
        if: ${{steps.vars.outputs.count == 23 && github.event.head_commit.message != 'Update progress'}}
        env:
          EMOTIONAL_ENDPOINT: ${{ secrets.EMOTIONAL_ENDPOINT }}
        run: |
          npm install node-fetch
          npm install form-data
          node .bit/tests/test.2.5.js --repo=${{github.event.repository.name}} --user=${{github.repository_owner}}

      - name: Check for branch
        if: ${{steps.vars.outputs.count > 23 && github.event.head_commit.message != 'Update progress'}}
        run: |
          node .bit/tests/wrongbranch.js
