name: Song 4 U
on:
  push:
    branches:
      - song4u

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Setup Node Environment
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install Dependencies
        run: |
          npm install minimist
          npm install node-fetch

      - name: Get Count
        id: vars
        run: echo ::set-output name=count::$(node ./.bit/scripts/getProgress.js --repo=${{github.event.repository.name}} --owner=${{github.repository_owner}} )

      - name: Step 26
        if: ${{steps.vars.outputs.count == 26 && github.event.head_commit.message != 'Update progress'}}
        env:
          SONGREC_ENDPOINT: ${{ secrets.SONGREC_ENDPOINT }}
        run: |
          npm install node-fetch
          node .bit/tests/test.2.6.js

      - name: Step 28
        if: ${{steps.vars.outputs.count == 28 && github.event.head_commit.message != 'Update progress'}}
        env:
          SONGREC_ENDPOINT: ${{ secrets.SONGREC_ENDPOINT }}
        run: |
          npm install node-fetch
          node .bit/tests/test.2.7.js

      - name: Step 30
        if: ${{steps.vars.outputs.count == 30 && github.event.head_commit.message != 'Update progress'}}
        env:
          SONGREC_ENDPOINT: ${{ secrets.SONGREC_ENDPOINT }}
        run: |
          npm install node-fetch
          node .bit/tests/test.2.8.js
      - name: Check for branch
        if: ${{steps.vars.outputs.count > 30 && github.event.head_commit.message != 'Update progress'}}
        run: |
          node .bit/tests/wrongbranch.js
