name: Week 1
on:
  push:
    branches:
      - week1

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Setup Node Environment
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Get Count
        id: vars
        run: echo ::set-output name=count::$(cat ./.bit/.progress)

      - name: Step 2
        if: ${{steps.vars.outputs.count == 1 && github.event.head_commit.message != 'Update progress'}}
        run: |
          node .bit/tests/test.1.2.js
      - name: Step 4
        if: ${{steps.vars.outputs.count == 3 && github.event.head_commit.message != 'Update progress'}}
        env:
          HACKERVOICE_ENDPOINT: ${{ secrets.HACKERVOICE_ENDPOINT }}
        run: |
          npm install node-fetch
          node .bit/tests/test.1.4.js
      - name: Step 5
        if: ${{steps.vars.outputs.count == 4 && github.event.head_commit.message != 'Update progress'}}
        env:
          HACKERVOICE_ENDPOINT: ${{ secrets.HACKERVOICE_ENDPOINT }}
        run: |
          npm install node-fetch
          node .bit/tests/test.1.5.js
      - name: Step 6
        if: ${{steps.vars.outputs.count == 5 && github.event.head_commit.message != 'Update progress'}}
        env:
          TWOCATZ_ENDPOINT: ${{ secrets.TWOCATZ_ENDPOINT }}
        run: |
          npm install node-fetch
          node .bit/tests/test.1.6.js
      - name: Step 7
        if: ${{steps.vars.outputs.count == 6 && github.event.head_commit.message != 'Update progress'}}
        env:
          TWOCATZ_ENDPOINT: ${{ secrets.TWOCATZ_ENDPOINT }}
        run: |
          npm install node-fetch
          node .bit/tests/test.1.7.js
      - name: Step 8
        if: ${{steps.vars.outputs.count == 7 && github.event.head_commit.message != 'Update progress'}}
        env:
          MORSE_ENDPOINT: ${{ secrets.MORSE_ENDPOINT }}
        run: |
          npm install node-fetch
          node .bit/tests/test.1.8.js
      - name: Check for branch
        if: ${{steps.vars.outputs.count == 9 && github.event.head_commit.message != 'Update progress'}}
        run: |
          node .bit/tests/wrongbranch.js