name: Week 3
on:
  push:
    branches:
      - week3

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Setup Node Environment
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Get Count
        id: vars
        run: echo ::set-output name=count::$(cat ./.bit/.progress)

      - name: Step 1
        if: ${{steps.vars.outputs.count == 18 && github.event.head_commit.message != 'Update progress'}}
        env:
          storage_account_connection_string: ${{ secrets.storage_account_connection_string }}
          container_name: ${{ secrets.container_name }}
        run: |
          npm install @azure/storage-blob
          node .bit/tests/test.3.1.js
      - name: Step 2
        if: ${{steps.vars.outputs.count == 19 && github.event.head_commit.message != 'Update progress'}}
        env:
          BUNNIMAGE_ENDPOINT: ${{ secrets.BUNNIMAGE_ENDPOINT }}
          container_name: ${{ secrets.container_name }}
          blob_url: ${{ secrets.blob_url }}
        run: |
          npm install node-fetch
          npm install form-data
          node .bit/tests/test.3.2.js
      - name: Step 3
        if: ${{steps.vars.outputs.count == 20 && github.event.head_commit.message != 'Update progress'}}
        env:
          BUNNIMAGE_ENDPOINT: ${{ secrets.BUNNIMAGE_ENDPOINT }}
          container_name: ${{ secrets.container_name }}
          blob_url: ${{ secrets.blob_url }}
        run: |
          npm install node-fetch
          npm install form-data
          node .bit/tests/test.3.3.js
      - name: Step 5
        if: ${{steps.vars.outputs.count == 22 && github.event.head_commit.message != 'Update progress'}}
        env:
          BUNNIMAGE_ENDPOINT: ${{ secrets.BUNNIMAGE_ENDPOINT }}
          BUNNIMAGE_ENDPOINT2: ${{ secrets.BUNNIMAGE_ENDPOINT2 }}
          container_name: ${{ secrets.container_name }}
          blob_url: ${{ secrets.blob_url }}
        run: |
          npm install node-fetch
          npm install form-data
          node .bit/tests/test.3.5.js
      - name: Step 6
        if: ${{steps.vars.outputs.count == 23 && github.event.head_commit.message != 'Update progress'}}
        env:
          DEEPSECRETS_ENDPOINT: ${{ secrets.DEEPSECRETS_ENDPOINT }}
        run: |
          npm install node-fetch
          node .bit/tests/test.3.6.js
      - name: Step 7
        if: ${{steps.vars.outputs.count == 24 && github.event.head_commit.message != 'Update progress'}}
        env:
          DEEPSECRETS_ENDPOINT: ${{ secrets.DEEPSECRETS_ENDPOINT }}
        run: |
          npm install node-fetch
          node .bit/tests/test.3.7.js
      - name: Step 8
        if: ${{steps.vars.outputs.count == 25 && github.event.head_commit.message != 'Update progress'}}
        env:
          DEEPSECRETS_ENDPOINT: ${{ secrets.DEEPSECRETS_ENDPOINT }}
        run: |
          npm install node-fetch
          node .bit/tests/test.3.8.js