name: Week 2
on:
  push:
    branches:
      - week2

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Setup Node Environment
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Get Count
        id: vars
        run: echo ::set-output name=count::$(cat ./.bit/.progress)

      - name: Step 2
        if: ${{steps.vars.outputs.count == 11 && github.event.head_commit.message != 'Update progress'}}
        env:
          EMOTIONAL_ENDPOINT: ${{ secrets.EMOTIONAL_ENDPOINT }}
        run: |
          npm install node-fetch
          npm install form-data
          node .bit/tests/test.2.2.js

      - name: Step 3
        if: ${{steps.vars.outputs.count == 12 && github.event.head_commit.message != 'Update progress'}}
        env:
          EMOTIONAL_ENDPOINT: ${{ secrets.EMOTIONAL_ENDPOINT }}
        run: |
          npm install node-fetch
          npm install form-data
          node .bit/tests/test.2.3.js

      - name: Step 4
        if: ${{steps.vars.outputs.count == 13 && github.event.head_commit.message != 'Update progress'}}
        env:
          EMOTIONAL_ENDPOINT: ${{ secrets.EMOTIONAL_ENDPOINT }}
        run: |
          npm install node-fetch
          npm install form-data
          node .bit/tests/test.2.4.js

      - name: Step 5
        if: ${{steps.vars.outputs.count == 14 && github.event.head_commit.message != 'Update progress'}}
        env:
          EMOTIONAL_ENDPOINT: ${{ secrets.EMOTIONAL_ENDPOINT }}
        run: |
          npm install node-fetch
          npm install form-data
          node .bit/tests/test.2.5.js

      - name: Step 6
        if: ${{steps.vars.outputs.count == 15 && github.event.head_commit.message != 'Update progress'}}
        env:
          SONGREC_ENDPOINT: ${{ secrets.SONGREC_ENDPOINT }}
        run: |
          npm install node-fetch
          node .bit/tests/test.2.6.js

      - name: Step 7
        if: ${{steps.vars.outputs.count == 16 && github.event.head_commit.message != 'Update progress'}}
        env:
          SONGREC_ENDPOINT: ${{ secrets.SONGREC_ENDPOINT }}
        run: |
          npm install node-fetch
          node .bit/tests/test.2.7.js

      - name: Step 8
        if: ${{steps.vars.outputs.count == 17 && github.event.head_commit.message != 'Update progress'}}
        env:
          SONGREC_ENDPOINT: ${{ secrets.SONGREC_ENDPOINT }}
        run: |
          npm install node-fetch
          node .bit/tests/test.2.8.js

