name: Syncing Your Cabin
on:
  push:
    branches:
      - null

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Setup Python Environment
        uses: actions/setup-python@v2
        with:
          python-version: 3.7

      - name: Getting Filenames
        run: |
          python .bit/scripts/start.py
      - name: Getting Descriptions
        run: |
          python .bit/scripts/parse.py
      - name: Creating Config Files
        run: |
          python .bit/scripts/create.py
          
      - name: Setup Git Config
        if: ${{github.event.head_commit.message != 'Initial commit'}}
        run: |
          git config user.name ${{ secrets.USERNAME }}
          git config user.email ${{ secrets.EMAIL }}
      - name: Commit Synced Changes
        if: ${{github.event.head_commit.message != 'Initial commit'}}
        run: |
          chmod +x .bit/scripts/commit.sh
          .bit/scripts/commit.sh
